environment: "virtual"

quotas_default:
  resources:
    pods: "4"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"

namespaces:
  jump-app-dev:
    networkpolicy:
      enabled: true
    quotas:
      enabled: true
      resources:
        secrets: "10"
        services: "10"
        services.loadbalancers: "2"
  jump-app-pre:
    quotas:
      enabled: true
    networkpolicy:
      enabled: false
  jump-app-pro: 
    quotas:
      enabled: false
    networkpolicy:
      enabled: true

networking:
  allow-pre-dev:
    orig: jump-app-pre
    dest: jump-app-dev
  allow-pro-pre:
    orig: jump-app-pro
    dest: jump-app-pre

argocd:
  enabled: true
  controller: openshift-gitops

ldap:
  url: "ldap://ldap.test.es:389/ou=users,dc=test,dc=test,dc=es?uid" 
  bindDN: "uid=appopenshift,ou=users,dc=test,dc=test,dc=es" 
  insecure: true

ingresscontrollers:
  des: 
    domain: apps.des.ocpabpd.test.test.es
    endpointPublishingStrategy:
      hostNetwork:
        httpPort: 8080
        httpsPort: 8443
        protocol: TCP
        statsPort: 1937
    namespaceSelector:
      matchLabels:
        testenv: des
    nodePlacement:
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/infra: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Equal
    replicas: 2

